### ISSUE TITLE
Is it still a thing ?

### ISSUE THREAD

**Issue by fabienfoerster** [TeamBrookie/DeltaSeries#2]
Bon normalment Betaseries sort une app en beta fin du mois de mai : https://www.betaseries.com/android

Mais je reste intéressé par une version Strobbienne de la chose ..

**Comment by etiennestrobbe** [comment]
je viens de lire cet issue.

**Comment by fabienfoerster** [comment]
Et ?


--
Fabien Foerster
Élève ingénieur à Polytech' Nice Sophia
Département Informatique - 5ème année

**Comment by fabienfoerster** [comment]
La version est sortie en public sur le Play Store : https://play.google.com/store/apps/details?id=com.betaseriesnative
Mais tu as toujours pas répondu, tu as peut etre répondu dans une autre discussion mais je m'en souviens pas ...
